// Mocks generated by Mockito 5.4.6 from annotations
// in zenigo/test/src/features/player/data/routine_repository_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:zenigo/src/features/player/data/routine_api.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [RoutineApi].
///
/// See the documentation for Mockito's code generation for more information.
class MockRoutineApi extends _i1.Mock implements _i2.RoutineApi {
  MockRoutineApi() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<Map<String, dynamic>>> fetchAllRoutines() =>
      (super.noSuchMethod(
            Invocation.method(#fetchAllRoutines, []),
            returnValue: _i3.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i3.Future<List<Map<String, dynamic>>>);

  @override
  _i3.Future<Map<String, dynamic>?> fetchRoutineById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#fetchRoutineById, [id]),
            returnValue: _i3.Future<Map<String, dynamic>?>.value(),
          )
          as _i3.Future<Map<String, dynamic>?>);

  @override
  _i3.Future<List<Map<String, dynamic>>> fetchBlocksForRoutine(
    String? routineId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#fetchBlocksForRoutine, [routineId]),
            returnValue: _i3.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i3.Future<List<Map<String, dynamic>>>);

  @override
  _i3.Future<Map<String, dynamic>> saveRoutine(
    Map<String, dynamic>? routineData,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#saveRoutine, [routineData]),
            returnValue: _i3.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i3.Future<Map<String, dynamic>>);

  @override
  _i3.Future<void> deleteRoutine(String? routineId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteRoutine, [routineId]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> deleteBlocksForRoutine(String? routineId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteBlocksForRoutine, [routineId]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<List<Map<String, dynamic>>> saveBlocks(
    List<Map<String, dynamic>>? blocksData,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#saveBlocks, [blocksData]),
            returnValue: _i3.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i3.Future<List<Map<String, dynamic>>>);
}
