// Mocks generated by Mockito 5.4.6 from annotations
// in zenigo/test/src/features/routine_editor/presentation/routine_editor_controller_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:zenigo/src/core/models/routine.dart' as _i2;
import 'package:zenigo/src/features/player/data/routine_repository.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeRoutine_0 extends _i1.SmartFake implements _i2.Routine {
  _FakeRoutine_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [RoutineRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockRoutineRepository extends _i1.Mock implements _i3.RoutineRepository {
  MockRoutineRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<List<_i2.Routine>> getAllRoutines() =>
      (super.noSuchMethod(
            Invocation.method(#getAllRoutines, []),
            returnValue: _i4.Future<List<_i2.Routine>>.value(<_i2.Routine>[]),
          )
          as _i4.Future<List<_i2.Routine>>);

  @override
  _i4.Future<_i2.Routine> getRoutineById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getRoutineById, [id]),
            returnValue: _i4.Future<_i2.Routine>.value(
              _FakeRoutine_0(this, Invocation.method(#getRoutineById, [id])),
            ),
          )
          as _i4.Future<_i2.Routine>);

  @override
  _i4.Future<_i2.Routine> saveRoutine(_i2.Routine? routine) =>
      (super.noSuchMethod(
            Invocation.method(#saveRoutine, [routine]),
            returnValue: _i4.Future<_i2.Routine>.value(
              _FakeRoutine_0(this, Invocation.method(#saveRoutine, [routine])),
            ),
          )
          as _i4.Future<_i2.Routine>);

  @override
  _i4.Future<void> deleteRoutine(String? routineId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteRoutine, [routineId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}
