// Mocks generated by Mockito 5.4.6 from annotations
// in zenigo/test/src/features/dashboard/presentation/dashboard_screen_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:mockito/mockito.dart' as _i1;
import 'package:zenigo/src/core/auth/auth_repository.dart' as _i8;
import 'package:zenigo/src/core/models/routine.dart' as _i2;
import 'package:zenigo/src/core/models/user_session.dart' as _i7;
import 'package:zenigo/src/core/models/user_stats.dart' as _i3;
import 'package:zenigo/src/features/player/data/routine_repository.dart' as _i4;
import 'package:zenigo/src/features/progress/data/progress_repository.dart'
    as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeRoutine_0 extends _i1.SmartFake implements _i2.Routine {
  _FakeRoutine_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUserStats_1 extends _i1.SmartFake implements _i3.UserStats {
  _FakeUserStats_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [RoutineRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockRoutineRepository extends _i1.Mock implements _i4.RoutineRepository {
  MockRoutineRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<List<_i2.Routine>> getAllRoutines() =>
      (super.noSuchMethod(
            Invocation.method(#getAllRoutines, []),
            returnValue: _i5.Future<List<_i2.Routine>>.value(<_i2.Routine>[]),
          )
          as _i5.Future<List<_i2.Routine>>);

  @override
  _i5.Future<_i2.Routine> getRoutineById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getRoutineById, [id]),
            returnValue: _i5.Future<_i2.Routine>.value(
              _FakeRoutine_0(this, Invocation.method(#getRoutineById, [id])),
            ),
          )
          as _i5.Future<_i2.Routine>);

  @override
  _i5.Future<_i2.Routine> saveRoutine(_i2.Routine? routine) =>
      (super.noSuchMethod(
            Invocation.method(#saveRoutine, [routine]),
            returnValue: _i5.Future<_i2.Routine>.value(
              _FakeRoutine_0(this, Invocation.method(#saveRoutine, [routine])),
            ),
          )
          as _i5.Future<_i2.Routine>);

  @override
  _i5.Future<void> deleteRoutine(String? routineId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteRoutine, [routineId]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);
}

/// A class which mocks [ProgressRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockProgressRepository extends _i1.Mock
    implements _i6.ProgressRepository {
  MockProgressRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<void> addSession(_i2.Routine? routine) =>
      (super.noSuchMethod(
            Invocation.method(#addSession, [routine]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<List<_i7.UserSession>> getSessionHistory() =>
      (super.noSuchMethod(
            Invocation.method(#getSessionHistory, []),
            returnValue: _i5.Future<List<_i7.UserSession>>.value(
              <_i7.UserSession>[],
            ),
          )
          as _i5.Future<List<_i7.UserSession>>);

  @override
  _i5.Stream<_i3.UserStats> watchUserStats() =>
      (super.noSuchMethod(
            Invocation.method(#watchUserStats, []),
            returnValue: _i5.Stream<_i3.UserStats>.empty(),
          )
          as _i5.Stream<_i3.UserStats>);

  @override
  _i5.Future<_i3.UserStats> getUserStats() =>
      (super.noSuchMethod(
            Invocation.method(#getUserStats, []),
            returnValue: _i5.Future<_i3.UserStats>.value(
              _FakeUserStats_1(this, Invocation.method(#getUserStats, [])),
            ),
          )
          as _i5.Future<_i3.UserStats>);
}

/// A class which mocks [AuthRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRepository extends _i1.Mock implements _i8.AuthRepository {
  MockAuthRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<void> signInWithEmail(String? email, String? password) =>
      (super.noSuchMethod(
            Invocation.method(#signInWithEmail, [email, password]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> signUpWithEmail(String? email, String? password) =>
      (super.noSuchMethod(
            Invocation.method(#signUpWithEmail, [email, password]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> signOut() =>
      (super.noSuchMethod(
            Invocation.method(#signOut, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);
}
